name: Ejecutar script Selenium pruebaOHMixtral

on: [push]

jobs:
  test_selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Instalar dependencias
      run: |
        sudo apt-get update        
        pip install selenium webdriver-manager
    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@v2
      with:
        # Especificamos la version de Chrome que vamos a usar
        chromedriver-version: '124.0.6367.60'
 
    - name: Ejecutar script Selenium
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & 
        
        cd cgi-bin/
        python pruebaOHMixtral.py
