name: Ejecutar script Selenium

on: [push]

jobs:
  test_selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Instalar dependencias
      run: |
        sudo apt-get update        
        pip install selenium webdriver-manager

    - name: Ejecutar script Selenium
      run: |
        python .\cgi-bin\pruebaOHMixtral.py
