name: Ejecutar script Selenium

on: [push]

jobs:
  test_selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Instalar dependencias
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        pip install selenium

    - name: Ejecutar script Selenium
      run: |
        python pruebaOHMixtral.py
